### ISSUE TITLE
Autocomplete: Browser build not working

### ISSUE THREAD

**Issue by tgaochn** [sourcegraph/cody#1191]
Autocomplete cannot be triggered in code-server ([code-server](https://github.com/coder/code-server/tree/main) is a web-based vscode).
Nothing shows up in the code and "Cody autocomplete trace view". 
The other functions seem fine in code-server.
Autocomplete works fine in my local vscode. 
![image](https://github.com/sourcegraph/cody/assets/22850831/cfc14b35-d1e7-4978-8b28-17fb320d418a)

**Comment by jdorfman** [comment]
@tgaochn thanks for reporting. 

Is this happening with similar functioning extensions on code-server or just Cody?

**Comment by philipp-spiess** [comment]
@tgaochn Heya! Thanks for reporting this.

Do you know what vs code version is used on the server setup? Did you see the loading indicator spin to indicate a request is being made? Additionally, can you take a look at the logs and send us anything that might pop up there? [How to access Cody logs](https://docs.sourcegraph.com/cody/capabilities#access-autocomplete-logs).

**Comment by tgaochn** [comment]
> @tgaochn thanks for reporting.
> 
> Is this happening with similar functioning extensions on code-server or just Cody?

copilot works fine in code-server:
![image](https://github.com/sourcegraph/cody/assets/22850831/e24cfca4-00bf-4eb9-9e25-f848241c2e1f)

**Comment by philipp-spiess** [comment]
@tgaochn Thanks! I was able to repro the issue locally too:

```
ERR lines(...).findLast is not a function: TypeError: lines(...).findLast is not a function
	at getPrevNonEmptyLine (/Users/philipp/.local/share/code-server/extensions/sourcegraph.cody-ai-0.12.2-universal/dist/extension.node.js:71913:68)
	at getCurrentDocContext (/Users/philipp/.local/share/code-server/extensions/sourcegraph.cody-ai-0.12.2-universal/dist/extension.node.js:72568:28)
	at InlineCompletionItemProvider.provideInlineCompletionItems (/Users/philipp/.local/share/code-server/extensions/sourcegraph.cody-ai-0.12.2-universal/dist/extension.node.js:73658:24)
	at pe.provideInlineCompletions (/opt/homebrew/Cellar/code-server/4.16.1/libexec/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:101:53406)
	at /opt/homebrew/Cellar/code-server/4.16.1/libexec/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:101:71451
	at se.s (/opt/homebrew/Cellar/code-server/4.16.1/libexec/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:101:62837)
	at se.$provideInlineCompletions (/opt/homebrew/Cellar/code-server/4.16.1/libexec/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:101:71437)
	at t.N (/opt/homebrew/Cellar/code-server/4.16.1/libexec/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:111:11199)
	at t.M (/opt/homebrew/Cellar/code-server/4.16.1/libexec/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:111:10965)
	at t.H (/opt/homebrew/Cellar/code-server/4.16.1/libexec/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:111:10007)
	at t.G (/opt/homebrew/Cellar/code-server/4.16.1/libexec/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:111:9122)
	at i.value (/opt/homebrew/Cellar/code-server/4.16.1/libexec/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:111:7952)
	at v.w (/opt/homebrew/Cellar/code-server/4.16.1/libexec/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:60:1902)
	at v.fire (/opt/homebrew/Cellar/code-server/4.16.1/libexec/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:60:2119)
	at fire (/opt/homebrew/Cellar/code-server/4.16.1/libexec/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:72:13931)
	at i.value (/opt/homebrew/Cellar/code-server/4.16.1/libexec/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:127:30923)
	at v.w (/opt/homebrew/Cellar/code-server/4.16.1/libexec/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:60:1902)
	at v.fire (/opt/homebrew/Cellar/code-server/4.16.1/libexec/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:60:2119)
	at fire (/opt/homebrew/Cellar/code-server/4.16.1/libexec/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:72:13931)
	at s.z (/opt/homebrew/Cellar/code-server/4.16.1/libexec/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:72:16976)
	at i.value (/opt/homebrew/Cellar/code-server/4.16.1/libexec/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:72:15428)
	at v.w (/opt/homebrew/Cellar/code-server/4.16.1/libexec/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:60:1902)
	at v.fire (/opt/homebrew/Cellar/code-server/4.16.1/libexec/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:60:2119)
	at i.acceptChunk (/opt/homebrew/Cellar/code-server/4.16.1/libexec/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:72:11705)
	at i.value (/opt/homebrew/Cellar/code-server/4.16.1/libexec/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:72:10992)
	at v.w (/opt/homebrew/Cellar/code-server/4.16.1/libexec/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:60:1902)
	at v.fire (/opt/homebrew/Cellar/code-server/4.16.1/libexec/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:60:2119)
	at v.u (/opt/homebrew/Cellar/code-server/4.16.1/libexec/lib/vscode/out/vs/workbench/api/node/extensionHostProcess.js:127:19064)
```

**Comment by philipp-spiess** [comment]
The reason for this is that the server side VS Code context is outdated (VS Code used Node 16 up until very recently) and we started to use node 18 already
