### ISSUE TITLE
Error when I run "npm run dev "

### ISSUE THREAD

**Issue by qiansheng2** [sourcegraph/cody#1449]
<img width="1308" alt="image" src="https://github.com/sourcegraph/cody/assets/5198358/9b82d2e2-173c-478c-9a0a-ddc5c88a047d">

How can I resolve this error?
My computer is macboook pro (Mac os sonoma 14.0 (23A344)),M1Max,64GB

Best regards.

**Comment by jdorfman** [comment]
Hi @qiansheng2 

Try running `pnpm install @sourcegraph/cody-shared` then `pnpm run dev`

If you still run into errors try `pnpm install` then `pnpm run dev`

**Comment by leiwen83** [comment]
same error.
And pnpm install @sourcegraph/cody-shared would not help.

```
[1] [commonjs--resolver] Failed to resolve entry for package "@sourcegraph/cody-shared". The package may have incorrect main/module/exports specified in its package.json.
[1] error during build:
[1] Error: Failed to resolve entry for package "@sourcegraph/cody-shared". The package may have incorrect main/module/exports specified in its package.json.
[1]     at packageEntryFailure (file:///Users/leiwen/dev/workdirs/misc/cody/node_modules/.pnpm/vite@4.4.3_@types+node@20.4.0/node_modules/vite/dist/node/chunks/dep-210e5610.js:28691:11)
[1]     at resolvePackageEntry (file:///Users/leiwen/dev/workdirs/misc/cody/node_modules/.pnpm/vite@4.4.3_@types+node@20.4.0/node_modules/vite/dist/node/chunks/dep-210e5610.js:28688:5)
[1]     at tryNodeResolve (file:///Users/leiwen/dev/workdirs/misc/cody/node_modules/.pnpm/vite@4.4.3_@types+node@20.4.0/node_modules/vite/dist/node/chunks/dep-210e5610.js:28422:20)
[1]     at Object.resolveId (file:///Users/leiwen/dev/workdirs/misc/cody/node_modules/.pnpm/vite@4.4.3_@types+node@20.4.0/node_modules/vite/dist/node/chunks/dep-210e5610.js:28183:28)
[1]     at file:///Users/leiwen/dev/workdirs/misc/cody/node_modules/.pnpm/rollup@3.26.2/node_modules/rollup/dist/es/shared/node-entry.js:25332:40
[1]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[1]     at async PluginDriver.hookFirstAndGetPlugin (file:///Users/leiwen/dev/workdirs/misc/cody/node_modules/.pnpm/rollup@3.26.2/node_modules/rollup/dist/es/shared/node-entry.js:25232:28)
[1]     at async resolveId (file:///Users/leiwen/dev/workdirs/misc/cody/node_modules/.pnpm/rollup@3.26.2/node_modules/rollup/dist/es/shared/node-entry.js:23907:26)
[1]     at async ModuleLoader.resolveId (file:///Users/leiwen/dev/workdirs/misc/cody/node_modules/.pnpm/rollup@3.26.2/node_modules/rollup/dist/es/shared/node-entry.js:24321:15)
[1]     at async Object.resolveId (file:///Users/leiwen/dev/workdirs/misc/cody/node_modules/.pnpm/vite@4.4.3_@types+node@20.4.0/node_modules/vite/dist/node/chunks/dep-210e5610.js:7990:10)
[1] pnpm run -s _build:webviews --mode development exited with code 1
[0] ✘ [ERROR] Could not resolve "@sourcegraph/cody-shared"
[0]
[0]     src/completions/tracer/traceView.ts:3:26:
[0]       3 │ import { isDefined } from '@sourcegraph/cody-shared'
[0]         ╵                           ~~~~~~~~~~~~~~~~~~~~~~~~~~
[0]
[0]   You can mark the path "@sourcegraph/cody-shared" as external to exclude it from the bundle, which will remove this error.
[0]
[0] ✘ [ERROR] Could not resolve "@sourcegraph/cody-shared"
[0]
[0]     src/completions/tree-sitter/ast-getters.ts:3:26:
[0]       3 │ import { isDefined } from '@sourcegraph/cody-shared'
[0]         ╵                           ~~~~~~~~~~~~~~~~~~~~~~~~~~
[0]
[0]   You can mark the path "@sourcegraph/cody-shared" as external to exclude it from the bundle, which will remove this error.
[0]
[0] 2 errors
```
