### ISSUE TITLE
bug: Clicking filenames in chat context list does not work (on Windows?)

### ISSUE THREAD

**Issue by DanTup** [sourcegraph/cody#2399]
### Version

main 2a00da01

### Describe the bug

Clicking this link doesn't work for me:

![image](https://github.com/sourcegraph/cody/assets/1078012/af82786b-2779-4819-8164-fb7c6b08ba87)

And I see this error:

```
rejected promise not handled within 1 second: Error: Invalid argument 'uriOrString' when running 'vscode.open', received: c:\Dev\Test Projects\dartcode_4895\lib\main.dart 
extensionHostProcess.js:147
stack trace: Error: Invalid argument 'uriOrString' when running 'vscode.open', received: c:\Dev\Test Projects\dartcode_4895\lib\main.dart 
	at c:\Users\danny\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:141:138142
	at Array.map (<anonymous>)
	at p.registerCommand.description (c:\Users\danny\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:141:138103)
	at d.h (c:\Users\danny\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:141:140094)
	at d.g (c:\Users\danny\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:141:139086)
	at d.executeCommand (c:\Users\danny\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:141:138993)
	at Object.executeCommand (c:\Users\danny\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:158:21333)
	at openFilePath (c:\Dev\Sourcegraph\cody\vscode\dist\extension.node.js:164413:26)
	at SimpleChatPanelProvider.onDidReceiveMessage (c:\Dev\Sourcegraph\cody\vscode\dist\extension.node.js:167591:15)
	at f.value (c:\Dev\Sourcegraph\cody\vscode\dist\extension.node.js:167490:79)
```

On the surface, the path looks correct.

### Expected behavior

File should open, no error in console.

**Comment by DanTup** [comment]
> Could it be due to change in VSCode from paths to URI?

I did wonder that - the current docs at https://code.visualstudio.com/api/references/commands#:~:text=of%20InlineValue%20objects-,vscode.open,-%2D%20Opens%20the%20provided say that the command expects a URI. I don't know if that's a recent change though.. I find a lot of issues with confusion between paths and URIs in VS Code - including [places that use "path" in the API to apparently now mean "path of a URI"](https://github.com/microsoft/vscode/issues/200359) :(

In any case, in [my fix](https://github.com/sourcegraph/cody/pull/2400) for this I actually remove this call because it seems redundant given the code that immediately follows it. It was just opening the document an extra time, but if it throws the other code wouldn't run.

**Comment by DanTup** [comment]
Reading https://github.com/microsoft/vscode/blob/242755e50a5b3c2deb468b5230c37b791582467d/src/vs/workbench/api/common/extHostApiCommands.ts#L400 makes it seem like it's always been this way, but this code must've worked at some point so I'm not sure what really happened here.

**Comment by RXminuS** [comment]
Hah, yeah I wondered why it did it twice as well. Thought there must have been some undocumented reason, but that makes sense then.

Maybe unrelated, but would be nice though if there was a better way of typing these commands because I've ran into it a few times as well where arguments change. I think you can just extend the vscode module like this:

```
declare module 'vscode' {
    declare namespace commands {
        export function executeCommand(command: 'vscode.open', path: vscode.URI): Thenable<void>
        export function executeCommand(command: 'hello-world', msg: string): Thenable<boolean>
    }
}
```

Could probably introduce a type with all possible command functions and then re-use the same to make the registration of them typesafe.

**Comment by DanTup** [comment]
Yeah, that would be great - even better if VS Code did it and kept it up-to-date (see https://github.com/microsoft/vscode/issues/110459 and add 👍 s!).

@umpox has scripts at https://github.com/umpox/vscode-tracker that dump all of the commands, but I don't know if there's a way to easily figure out the argument kinds to automate it there.

**Comment by RXminuS** [comment]
Yeah, that'd be awesome. Might have a look 😊 I'm also thinking about merging it without custom commands in this repo

**Comment by DanTup** [comment]
This bug was fixed by some recent changes to use URIs everywhere.

https://github.com/sourcegraph/cody/assets/1078012/928dd4d4-a566-4816-99ec-ad65ed2ac682
