### ISSUE TITLE
bug: Cody does not work in WSL 2 on Windows

### ISSUE THREAD

**Issue by scho-to** [sourcegraph/cody#2429]
### Version

1.79.2

### Describe the bug

When using Cody in a WSL 2 (Ubuntu 22.04 LTS) instance of VS Code on Windows 11, nothing seems to work, as it can't find the commands. Autocomplete doesn't work too. There is no icon in the status bar either.

If I run Cody without WSL 2, it does work as intended withouth any noticed problems.

### Expected behavior

I can use Cody in WSL 2 instances.

### Additional context

![image](https://github.com/sourcegraph/cody/assets/58687214/977ca7f9-a8e1-43f6-82d2-b90c6cff1516)

![image](https://github.com/sourcegraph/cody/assets/58687214/e0af5106-ea19-4a83-828a-c1edd4aab7e3)

**Comment by DanTup** [comment]
I tried but couldn't reproduce this:

![image](https://github.com/sourcegraph/cody/assets/1078012/460ca220-f66f-4d20-998a-c4e75da9fbf0)

Are there any errors in the console if you click:

- Help -> Toggle Developer Tools
- Click on the "Console" tab

**Comment by scho-to** [comment]
Hi @DanTup ,

this is the error from the console tab:
`ERR [Extension Host] TypeError: entry?.interactions?.findLast is not a function
	at /home/USER/.vscode-server/extensions/sourcegraph.cody-ai-1.0.4/dist/extension.node.js:163793:51
	at Array.forEach (<anonymous>)
	at createCodyChatTreeItems (/home/USER/.vscode-server/extensions/sourcegraph.cody-ai-1.0.4/dist/extension.node.js:163792:22)
	at ChatPanelsManager.updateTreeViewHistory (/home/USER/.vscode-server/extensions/sourcegraph.cody-ai-1.0.4/dist/extension.node.js:168701:44)
	at ChatPanelsManager.syncAuthStatus (/home/USER/.vscode-server/extensions/sourcegraph.cody-ai-1.0.4/dist/extension.node.js:168588:16)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async ChatManager.syncAuthStatus (/home/USER/.vscode-server/extensions/sourcegraph.cody-ai-1.0.4/dist/extension.node.js:169170:5)
	at async register (/home/USER/.vscode-server/extensions/sourcegraph.cody-ai-1.0.4/dist/extension.node.js:179405:3)
	at async start3 (/home/USER/.vscode-server/extensions/sourcegraph.cody-ai-1.0.4/dist/extension.node.js:179251:49)
	at async activate (/home/USER/.vscode-server/extensions/sourcegraph.cody-ai-1.0.4/dist/extension.node.js:179701:24)
	at async b.n (/home/USER/.vscode-server/bin/695af09…/out/vs/workbench/api/node/extensionHostProcess.js:98:6644)
	at async b.m (/home/USER/.vscode-server/bin/695af09…/out/vs/workbench/api/node/extensionHostProcess.js:98:6607)
	at async b.l (/home/USER/.vscode-server/bin/695af09…/out/vs/workbench/api/node/extensionHostProcess.js:98:6064)`
	
	I have reinstalled Cody Extension several times, it doesn't help. I also tried the "Pre-Release" Version.

**Comment by scho-to** [comment]
Hello @DanTup ,

i just noticed, that I wasn't running the latest vs code version.. I just updated vscode to the latest version, now it is working in WSL 2.

I can not explain, why it was using a old VS code version.. I am pretty sure, I checked the version before posting this bug.

**Comment by DanTup** [comment]
Thanks for the update. I'm not sure why the VS Code version impacted this, but glad to hear it's working. If you see the issue again please do post back!
