### ISSUE TITLE
bug: Resuming a chat fails with error

### ISSUE THREAD

**Issue by chwarwick** [sourcegraph/cody#3421]
### Version

v1.8.3

### Describe the bug

Resume a previous chat and type a new message then the chat will display an error "cannot read properties of undefined (reading 'line')"

### Expected behavior

chat continues

### Additional context

![image](https://github.com/sourcegraph/cody/assets/6098507/728402f0-fca1-4c06-89a8-9f23c4f66673)

**Comment by dominiccooney** [comment]
I caught a callstack here:

```
[Extension Host] exception: {"exception.type":"TypeError","exception.message":"Cannot read properties of undefined (reading 'line')","exception.stacktrace":"TypeError: Cannot read properties of undefined (reading 'line')\n\tat contextItemId (/Users/dpc/.vscode/extensions/sourcegraph.cody-ai-1.8.3/dist/extension.node.js:136031:55)\n\tat PromptBuilder.tryAddContext (/Users/dpc/.vscode/extensions/sourcegraph.cody-ai-1.8.3/dist/extension.node.js:135994:18)\n\tat /Users/dpc/.vscode/extensions/sourcegraph.cody-ai-1.8.3/dist/extension.node.js:136124:48\n\tat /Users/dpc/.vscode/extensions/sourcegraph.cody-ai-1.8.3/dist/extension.node.js:118664:24\n\tat AsyncLocalStorage.run (node:async_hooks:338:14)\n\tat AsyncLocalStorageContextManager.with (/Users/dpc/.vscode/extensions/sourcegraph.cody-ai-1.8.3/dist/extension.node.js:108948:40)\n\tat _ContextAPI.with (/Users/dpc/.vscode/extensions/sourcegraph.cody-ai-1.8.3/dist/extension.node.js:17855:46)\n\tat Tracer.startActiveSpan (/Users/dpc/.vscode/extensions/sourcegraph.cody-ai-1.8.3/dist/extension.node.js:110116:32)\n\tat ProxyTracer.startActiveSpan (/Users/dpc/.vscode/extensions/sourcegraph.cody-ai-1.8.3/dist/extension.node.js:18101:24)\n\tat wrapInActiveSpan2 (/Users/dpc/.vscode/extensions/sourcegraph.cody-ai-1.8.3/dist/extension.node.js:118653:18)\n\tat DefaultPrompter.makePrompt (/Users/dpc/.vscode/extensions/sourcegraph.cody-ai-1.8.3/dist/extension.node.js:136090:12)\n\tat SimpleChatPanelProvider.buildPrompt (/Users/dpc/.vscode/extensions/sourcegraph.cody-ai-1.8.3/dist/extension.node.js:136741:64)\n\tat /Users/dpc/.vscode/extensions/sourcegraph.cody-ai-1.8.3/dist/extension.node.js:136494:38"}
```

I can't reliably reproduce this.

**Comment by chwarwick** [comment]
The key to reproducing appears to be to use resume a chat that had remote context added to it. 
My setup is: 
v1.8.3
Connected to s2
Restarting a chat who's previous message had remote context with it.

Here's a video 

https://github.com/sourcegraph/cody/assets/6098507/72d9d5f1-4c8d-4d14-9a90-dd2c26438c79


Grabbed this from Extension host logs:
```
 Cannot add a user message after a user message
	at SimpleChatModel.addHumanMessage (/Users/chriswarwick/.vscode/extensions/sourcegraph.cody-ai-1.8.3/dist/extension.node.js:124157:13)
	at /Users/chriswarwick/.vscode/extensions/sourcegraph.cody-ai-1.8.3/dist/extension.node.js:136441:24
	at NoopContextManager.with (/Users/chriswarwick/.vscode/extensions/sourcegraph.cody-ai-1.8.3/dist/extension.node.js:17794:19)
	at _ContextAPI.with (/Users/chriswarwick/.vscode/extensions/sourcegraph.cody-ai-1.8.3/dist/extension.node.js:17855:46)
	at NoopTracer.startActiveSpan (/Users/chriswarwick/.vscode/extensions/sourcegraph.cody-ai-1.8.3/dist/extension.node.js:18071:31)
	at ProxyTracer.startActiveSpan (/Users/chriswarwick/.vscode/extensions/sourcegraph.cody-ai-1.8.3/dist/extension.node.js:18101:24)
	at /Users/chriswarwick/.vscode/extensions/sourcegraph.cody-ai-1.8.3/dist/extension.node.js:136430:14
	at NoopContextManager.with (/Users/chriswarwick/.vscode/extensions/sourcegraph.cody-ai-1.8.3/dist/extension.node.js:17794:19)
	at _ContextAPI.with (/Users/chriswarwick/.vscode/extensions/sourcegraph.cody-ai-1.8.3/dist/extension.node.js:17855:46)
	at NoopTracer.startActiveSpan (/Users/chriswarwick/.vscode/extensions/sourcegraph.cody-ai-1.8.3/dist/extension.node.js:18071:31)
	at ProxyTracer.startActiveSpan (/Users/chriswarwick/.vscode/extensions/sourcegraph.cody-ai-1.8.3/dist/extension.node.js:18101:24)
	at SimpleChatPanelProvider.handleUserMessageSubmission (/Users/chriswarwick/.vscode/extensions/sourcegraph.cody-ai-1.8.3/dist/extension.node.js:136404:19)
	at SimpleChatPanelProvider.onDidReceiveMessage (/Users/chriswarwick/.vscode/extensions/sourcegraph.cody-ai-1.8.3/dist/extension.node.js:136271:20)
	at w.value (/Users/chriswarwick/.vscode/extensions/sourcegraph.cody-ai-1.8.3/dist/extension.node.js:137029:27)
	at n.y (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:1902)
	at n.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:2119)
	at E.$onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:142:14051)
	at s.S (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:147:5519)
	at s.Q (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:147:5285)
	at s.M (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:147:4375)
	at s.L (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:147:3593)
	at w.value (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:147:2241)
	at n.y (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:1902)
	at n.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:2119)
	at r.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:105:14091)
	at w.value (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:173:8050)
	at n.y (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:1902)
	at n.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:2119)
	at r.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:105:14091)
	at MessagePortMain.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:173:6330)
	at MessagePortMain.emit (node:events:514:28)
	at MessagePortMain.emit (node:domain:489:12)
	at Object.emit (node:electron/js2c/utility_init:2:2285)
2024-03-20 07:42:30.298 [error] Error: Cannot add a user message after a user message
	at SimpleChatModel.addHumanMessage (/Users/chriswarwick/.vscode/extensions/sourcegraph.cody-ai-1.8.3/dist/extension.node.js:124157:13)
	at /Users/chriswarwick/.vscode/extensions/sourcegraph.cody-ai-1.8.3/dist/extension.node.js:136441:24
	at NoopContextManager.with (/Users/chriswarwick/.vscode/extensions/sourcegraph.cody-ai-1.8.3/dist/extension.node.js:17794:19)
	at _ContextAPI.with (/Users/chriswarwick/.vscode/extensions/sourcegraph.cody-ai-1.8.3/dist/extension.node.js:17855:46)
	at NoopTracer.startActiveSpan (/Users/chriswarwick/.vscode/extensions/sourcegraph.cody-ai-1.8.3/dist/extension.node.js:18071:31)
	at ProxyTracer.startActiveSpan (/Users/chriswarwick/.vscode/extensions/sourcegraph.cody-ai-1.8.3/dist/extension.node.js:18101:24)
	at /Users/chriswarwick/.vscode/extensions/sourcegraph.cody-ai-1.8.3/dist/extension.node.js:136430:14
	at NoopContextManager.with (/Users/chriswarwick/.vscode/extensions/sourcegraph.cody-ai-1.8.3/dist/extension.node.js:17794:19)
	at _ContextAPI.with (/Users/chriswarwick/.vscode/extensions/sourcegraph.cody-ai-1.8.3/dist/extension.node.js:17855:46)
	at NoopTracer.startActiveSpan (/Users/chriswarwick/.vscode/extensions/sourcegraph.cody-ai-1.8.3/dist/extension.node.js:18071:31)
	at ProxyTracer.startActiveSpan (/Users/chriswarwick/.vscode/extensions/sourcegraph.cody-ai-1.8.3/dist/extension.node.js:18101:24)
	at SimpleChatPanelProvider.handleUserMessageSubmission (/Users/chriswarwick/.vscode/extensions/sourcegraph.cody-ai-1.8.3/dist/extension.node.js:136404:19)
	at SimpleChatPanelProvider.onDidReceiveMessage (/Users/chriswarwick/.vscode/extensions/sourcegraph.cody-ai-1.8.3/dist/extension.node.js:136271:20)
	at w.value (/Users/chriswarwick/.vscode/extensions/sourcegraph.cody-ai-1.8.3/dist/extension.node.js:137029:27)
	at n.y (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:1902)
	at n.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:2119)
	at E.$onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:142:14051)
	at s.S (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:147:5519)
	at s.Q (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:147:5285)
	at s.M (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:147:4375)
	at s.L (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:147:3593)
	at w.value (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:147:2241)
	at n.y (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:1902)
	at n.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:2119)
	at r.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:105:14091)
	at w.value (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:173:8050)
	at n.y (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:1902)
	at n.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:80:2119)
	at r.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:105:14091)
	at MessagePortMain.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:173:6330)
	at MessagePortMain.emit (node:events:514:28)
	at MessagePortMain.emit (node:domain:489:12)
	at Object.emit (node:electron/js2c/utility_init:2:2285)
```

**Comment by chwarwick** [comment]
possibly related https://github.com/sourcegraph/cody/pull/3394
