### ISSUE TITLE
VS Code: Cody stuck in 'Formatting...' when user run Document Code for a Java function.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/cody#3952]
### Version

v1.14.0

### Describe the bug

Platform: MacOS

**Steps to reproduce:**

1. Have Cody plugin installed in your VS Code editor
2. Login to Cody with Pro user
3. Open a Java source code file
4. Select code snippet from any function i.e. bubbleSort()
5. Right click, and select Cody > Document Code

### Observed behavior:
Documentation will be added but Cody keep showing 'Formatting...' never finish the process

### Expected behavior

Cody should not be stuck at 'Formatting...'

### Additional context

**Video link:**

https://drive.google.com/file/d/1QDoeF7ToYf14RgnKN0d9a70jmAJXrXpf/view?usp=drive_link

**Comment by DrNeutron** [comment]
I have the same issue in python use of cody in VS Code.  Same symptoms as the video except in my case I also get an error pop up saying "Unexpected error in LSP server, see server's logs for details" Source Black Formatter.  The same error happens with both Black and Ruff.

**Comment by jeronimd** [comment]
same, while using autopep8


Traceback (most recent call last):
  File "c:\Users\David\.vscode\extensions\ms-python.autopep8-2024.0.0\bundled\libs\pygls\protocol\json_rpc.py", line 443, in data_received
    self._data_received(data)
  File "c:\Users\David\.vscode\extensions\ms-python.autopep8-2024.0.0\bundled\libs\pygls\protocol\json_rpc.py", line 475, in _data_received
    json.loads(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 359, in loads
    return cls(**kw).decode(s)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
  File "c:\Users\David\.vscode\extensions\ms-python.autopep8-2024.0.0\bundled\libs\pygls\protocol\json_rpc.py", line 344, in _deserialize_message
    raise JsonRpcInvalidParams() from exc
pygls.exceptions.JsonRpcInvalidParams: Invalid Params

**Comment by umpox** [comment]
Thanks for reporting!

Will be fixed by these PRs:
https://github.com/sourcegraph/cody/pull/4113
https://github.com/sourcegraph/cody/pull/4111
