### ISSUE TITLE
bug: completion error: Expected ',' or ']' after array element in JSON

### ISSUE THREAD

**Issue by vbehar** [sourcegraph/cody#4021]
### Version

v1.16.0

### Describe the bug

sometimes, cody fails to generate completion when using ollama. I get the following error in the logs:

```
█ CompletionLogger:onError: {"type":"code-completion","endpoint":"https://ollama-internal-host/api/generate","status":"error","duration":3439,"err":"Expected ',' or ']' after array element in JSON at position 11998 (line 1 column 11999)"}  {
  "params": {
    "prompt": "<｜fim▁begin｜>//  Path: path/to/file.go\nFILE CONTENT<｜fim▁hole｜>\nMORE CONTENT\n<｜fim▁end｜>",
    "template": "{{ .Prompt }}",
    "model": "deepseek-coder:6.7b-base-q4_K_M",
    "options": {
      "stop": [
        "\n",
        "<｜fim▁begin｜>",
        "<｜fim▁hole｜>",
        "<｜fim▁end｜>"
      ],
      "temperature": 0.6,
      "top_k": 30,
      "top_p": 0.2,
      "num_predict": 256,
      "num_gpu": 99,
      "repeat_penalty": 1.1,
      "num_ctx": 4096
    }
  }
}
█ getInlineCompletions:error: Expected ',' or ']' after array element in JSON at position 11998 (line 1 column 11999) SyntaxError: Expected ',' or ']' after array element in JSON at position 11998 (line 1 column 11999)
	at JSON.parse (<anonymous>)
	at Object.complete (/Users/vbehar/.vscode/extensions/sourcegraph.cody-ai-1.16.0/dist/extension.node.js:338107:29)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async generatorWithTimeout (/Users/vbehar/.vscode/extensions/sourcegraph.cody-ai-1.16.0/dist/extension.node.js:345355:31)
	at async fetchAndProcessDynamicMultilineCompletions (/Users/vbehar/.vscode/extensions/sourcegraph.cody-ai-1.16.0/dist/extension.node.js:363614:45)
	at async Promise.all (index 0)
	at async zipGenerators (/Users/vbehar/.vscode/extensions/sourcegraph.cody-ai-1.16.0/dist/extension.node.js:345321:17)
	at async generateCompletions (/Users/vbehar/.vscode/extensions/sourcegraph.cody-ai-1.16.0/dist/extension.node.js:363999:26) {
  "error": {}
}
█ logEvent (telemetry disabled): CodyVSCodeExtension:completion:error  {
  "details": "VSCode",
  "properties": {
    "message": "Expected ',' or ']' after array element in JSON at position 11998 (line 1 column 11999)",
    "count": 1
  },
  "opts": {
    "agent": true,
    "hasV2Event": true
  }
}
█ telemetry-v2: recordEvent: cody.completion/error  {
  "parameters": {
    "version": 0,
    "metadata": [
      {
        "key": "count",
        "value": 1
      }
    ],
    "privateMetadata": {
      "message": "Expected ',' or ']' after array element in JSON at position 11998 (line 1 column 11999)"
    }
  },
  "timestamp": "2024-05-02T13:10:11.029Z"
}
```

note that most of the completion requests are successful, but some of them fail

### Expected behavior

no failure

**Comment by dominiccooney** [comment]
@valerybugakov should have fixed this in #4066
