### ISSUE TITLE
bug: Cody constantly causing WebStorm to freeze

### ISSUE THREAD

**Issue by JJPowell** [sourcegraph/cody#5582]
WebStorm version: 2024.2.1 (this was also happening on 2022.2.1)
Cody version: 7.0.2

It's nearly constant. If I'm coding and using autocomplete it happens anywhere between2-10 minutes of work and I end up losing a few lines of code every time. When I turn off autocomplete and just use the prompt window it happens a lot less often.

**Comment by ToanPV90** [comment]
Experiencing the same issue with IntelliJ Idea 2021.2.1.

**Comment by sbreiler** [comment]
PhpStorm: 2024.2.1 
Cody: 7.0.2

Since updating Cody from 7.0.1 to 7.0.2, PhpStorm randomly freezes, affecting both my main project and a second project running in a parallel window. The freezes occurred after I reordered imports in a TypeScript file using `CTRL`+`SHIFT`+`ARROW UP` and again when I pasted content in another TypeScript file.

**Comment by ivsokol** [comment]
It also happens on IDEA Community Edition. I managed to pull thread dump


```
"AWT-EventQueue-0" prio=0 tid=0x0 nid=0x0 blocked
     java.lang.Thread.State: BLOCKED
 on com.sourcegraph.cody.statusbar.CodyStatusService@55a8b515 owned by "ApplicationImpl pooled thread 16" Id=184
	at com.sourcegraph.cody.statusbar.CodyStatusService.onCodyAutocompleteStatus(CodyStatusService.kt:24)
	at com.sourcegraph.cody.statusbar.CodyStatusService$Companion.notifyApplication(CodyStatusService.kt:111)
	at com.sourcegraph.cody.autocomplete.CodyAutocompleteManager.triggerAutocompleteAsync(CodyAutocompleteManager.kt:241)
	at com.sourcegraph.cody.autocomplete.CodyAutocompleteManager.triggerAutocomplete(CodyAutocompleteManager.kt:192)
	at com.sourcegraph.cody.editor.CodyLookupListener$activeLookupChanged$1.uiRefreshed(CodyLookupListener.kt:31)
	at com.intellij.codeInsight.lookup.impl.LookupImpl.fireUiRefreshed(LookupImpl.java:1040)
	at com.intellij.codeInsight.lookup.impl.LookupImpl.refreshUi(LookupImpl.java:1241)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.hideAutopopupIfMeaningless(CompletionProgressIndicator.java:732)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.updateLookup(CompletionProgressIndicator.java:456)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.lambda$stop$6(CompletionProgressIndicator.java:719)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator$$Lambda/0x00000008032d06b0.run(Unknown Source)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:229)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runIntendedWriteActionOnCurrentThread$lambda$1(AnyThreadWriteThreadingSupport.kt:184)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport$$Lambda/0x0000000800918f20.compute(Unknown Source)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:84)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runIntendedWriteActionOnCurrentThread(AnyThreadWriteThreadingSupport.kt:183)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:836)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:424)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWithImplicitRead(AnyThreadWriteThreadingSupport.kt:122)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithImplicitRead(ApplicationImpl.java:1162)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:78)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:119)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at com.intellij.openapi.application.impl.FlushQueue$$Lambda/0x0000000800560d18.run(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:728)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.base@21.0.3/java.security.AccessController.executePrivileged(AccessController.java:778)
	at java.base@21.0.3/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base@21.0.3/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:750)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:696)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$16(IdeEventQueue.kt:590)
	at com.intellij.ide.IdeEventQueue$$Lambda/0x0000000800a91000.run(Unknown Source)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWithoutImplicitRead(AnyThreadWriteThreadingSupport.kt:117)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:590)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:73)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1$1.compute(IdeEventQueue.kt:357)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1$1.compute(IdeEventQueue.kt:356)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:843)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.invoke(IdeEventQueue.kt:356)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.invoke(IdeEventQueue.kt:351)
	at com.intellij.ide.IdeEventQueueKt$performActivity$runnableWithWIL$1.invoke$lambda$0(IdeEventQueue.kt:1035)
	at com.intellij.ide.IdeEventQueueKt$performActivity$runnableWithWIL$1$$Lambda/0x0000000800a92000.run(Unknown Source)
	at com.intellij.openapi.application.WriteIntentReadAction.lambda$run$0(WriteIntentReadAction.java:24)
	at com.intellij.openapi.application.WriteIntentReadAction$$Lambda/0x0000000800a92d88.compute(Unknown Source)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:84)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteIntentReadAction(ApplicationImpl.java:910)
	at com.intellij.openapi.application.WriteIntentReadAction.compute(WriteIntentReadAction.java:55)
	at com.intellij.openapi.application.WriteIntentReadAction.run(WriteIntentReadAction.java:23)
	at com.intellij.ide.IdeEventQueueKt$performActivity$runnableWithWIL$1.invoke(IdeEventQueue.kt:1035)
	at com.intellij.ide.IdeEventQueueKt$performActivity$runnableWithWIL$1.invoke(IdeEventQueue.kt:1035)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1036)
	at com.intellij.ide.IdeEventQueueKt$$Lambda/0x0000000800a8bc08.run(Unknown Source)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1036)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$10(IdeEventQueue.kt:351)
	at com.intellij.ide.IdeEventQueue$$Lambda/0x0000000800a8b028.run(Unknown Source)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:397)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

```

**Comment by mkondratek** [comment]
Hello 👋 I am sorry you encountered this issue 🙇 
Thank you for the report, and thank you a lot for the provided details 💪 this is super helpful

You can try to update the plugin to the newest available versions that is: 👉  [7.0.6](https://plugins.jetbrains.com/plugin/9682-cody-ai-coding-assistant-with-autocomplete--chat/versions/stable/605595?noRedirect=true)  👈

**Comment by mkondratek** [comment]
Can you please provide more details about your env? You can open About IntelliJ IDEA and copy and paste it here. 
Esp. I am interested about your OS.

**Comment by mkondratek** [comment]
I tried to run a dev run with 2024.2.1 and WebStorm for 7.0.2. We were using Gradle IntelliJ Plugin v1 back then and it's impossible to use WS in a dev run. 

I am going to try  7.0.6 with WebStorm...

**Comment by mkondratek** [comment]
Looking at the thread dump it seems that we achieved a deadlock somewhere here:
```
  fun onCodyAutocompleteStatus(codyStatus: CodyStatus) {
    val notify =
        synchronized(this) {
          val oldStatus = status
          status = codyStatus
          return@synchronized oldStatus != codyStatus
        }
    if (notify) {
      updateCodyStatusBarIcons()
    }
  }
```

I do not recall any recent changes there. On the other hand we did not experience this issue (however we use IU and IC mostly). 

---

Please try to update the plugin.
I am going to investigate it further on Monday.

**Comment by sbreiler** [comment]
It runs fine with 7.0.6 for me, thanks!

**Comment by mkondratek** [comment]
Thank you for verifying 🚀 

I've tested WS 2024.2 with both plugin versions 7.0.2 and 7.0.6, and I was unable to reproduce the issue. Based on this, it seems that **updating the plugin resolves the problem**.

To help ensure everyone can continue without issues, I kindly recommend updating to the latest plugin version. Please let me know if you encounter any further difficulties.
