### ISSUE TITLE
fail to build from source

### ISSUE THREAD

**Issue by leiwen83** [sourcegraph/cody#934]
Hi,

I try build cody directly from source, but met below error:
```
[0] ✘ [ERROR] Could not resolve "@sourcegraph/cody-shared"
[0]
[0]     src/completions/tracer/traceView.ts:3:26:
[0]       3 │ import { isDefined } from '@sourcegraph/cody-shared'
[0]         ╵                           ~~~~~~~~~~~~~~~~~~~~~~~~~~
[0]
[0]   You can mark the path "@sourcegraph/cody-shared" as external to exclude it from the bundle, which will remove this error.
[0]
[0] 1 error
[0] pnpm run -s _build:esbuild:desktop exited with code 1
[1] ✓ 51 modules transformed.
[1] ✓ built in 739ms
[1] [commonjs--resolver] Failed to resolve entry for package "@sourcegraph/cody-shared". The package may have incorrect main/module/exports specified in its package.json.
[1] error during build:
[1] Error: Failed to resolve entry for package "@sourcegraph/cody-shared". The package may have incorrect main/module/exports specified in its package.json.
```

How to fix it?

**Comment by philipp-spiess** [comment]
@leiwen83 Hey there! We're using `pnpm` to manage dependencies. What's the output of `pnpm install` in the root of the cody package for you? It does look like something in the dependency setup is screwed up.

**Comment by leiwen83** [comment]
> @leiwen83 Hey there! We're using `pnpm` to manage dependencies. What's the output of `pnpm install` in the root of the cody package for you? It does look like something in the dependency setup is screwed up.

Hi @philipp-spiess 

I follow the insturction to use "pnpm install && cd vscode && pnpm run dev" and the whole message is as below.

```
# pnpm install
 WARN  Unsupported engine: wanted: {"node":"^v20.4.0"} (current: {"node":"v16.20.2","pnpm":"8.7.4"})
completions-review-tool                  |  WARN  Unsupported engine: wanted: {"node":">=v18.17.0"} (current: {"node":"v16.20.2","pnpm":"8.7.4"})
Scope: all 12 workspace projects
Lockfile is up to date, resolution step is skipped
Already up to date
vscode postinstall$ pnpm download-wasm
│ > cody-ai@0.10.0 download-wasm /data/aigc/workset/code/cody/vscode
│ > ts-node-transpile-only ./scripts/download-wasm-modules.ts
│ All wasm modules are in place, have a good day!
└─ Done in 688ms
Done in 1.6s
# cd vscode/
# pnpm run dev

> cody-ai@0.10.0 dev /data/aigc/workset/code/cody/vscode
> pnpm run -s dev:desktop

[1] vite v4.4.3 building for development...
[1] transforming...
[0] All wasm modules are in place, have a good day!
[0] ✘ [ERROR] Could not resolve "@sourcegraph/cody-shared"
[0]
[0]     src/completions/tracer/traceView.ts:3:26:
[0]       3 │ import { isDefined } from '@sourcegraph/cody-shared'
[0]         ╵                           ~~~~~~~~~~~~~~~~~~~~~~~~~~
[0]
[0]   You can mark the path "@sourcegraph/cody-shared" as external to exclude it from the bundle, which will remove this error.
[0]
[0] 1 error
[0] pnpm run -s _build:esbuild:desktop exited with code 1
[1] ✓ 37 modules transformed.
[1] ✓ built in 547ms
[1] [commonjs--resolver] Failed to resolve entry for package "@sourcegraph/cody-shared". The package may have incorrect main/module/exports specified in its package.json.
[1] error during build:
[1] Error: Failed to resolve entry for package "@sourcegraph/cody-shared". The package may have incorrect main/module/exports specified in its package.json.
[1]     at packageEntryFailure (file:///data/aigc/workset/code/cody/node_modules/.pnpm/vite@4.4.3_@types+node@20.4.0/node_modules/vite/dist/node/chunks/dep-210e5610.js:28691:11)
[1]     at resolvePackageEntry (file:///data/aigc/workset/code/cody/node_modules/.pnpm/vite@4.4.3_@types+node@20.4.0/node_modules/vite/dist/node/chunks/dep-210e5610.js:28688:5)
[1]     at tryNodeResolve (file:///data/aigc/workset/code/cody/node_modules/.pnpm/vite@4.4.3_@types+node@20.4.0/node_modules/vite/dist/node/chunks/dep-210e5610.js:28422:20)
[1]     at Object.resolveId (file:///data/aigc/workset/code/cody/node_modules/.pnpm/vite@4.4.3_@types+node@20.4.0/node_modules/vite/dist/node/chunks/dep-210e5610.js:28183:28)
[1]     at file:///data/aigc/workset/code/cody/node_modules/.pnpm/rollup@3.26.2/node_modules/rollup/dist/es/shared/node-entry.js:25332:40
[1]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[1]     at async PluginDriver.hookFirstAndGetPlugin (file:///data/aigc/workset/code/cody/node_modules/.pnpm/rollup@3.26.2/node_modules/rollup/dist/es/shared/node-entry.js:25232:28)
[1]     at async resolveId (file:///data/aigc/workset/code/cody/node_modules/.pnpm/rollup@3.26.2/node_modules/rollup/dist/es/shared/node-entry.js:23907:26)
[1]     at async ModuleLoader.resolveId (file:///data/aigc/workset/code/cody/node_modules/.pnpm/rollup@3.26.2/node_modules/rollup/dist/es/shared/node-entry.js:24321:15)
[1]     at async Object.resolveId (file:///data/aigc/workset/code/cody/node_modules/.pnpm/vite@4.4.3_@types+node@20.4.0/node_modules/vite/dist/node/chunks/dep-210e5610.js:7990:10)
[1] pnpm run -s _build:webviews --mode development exited with code 1
 ELIFECYCLE  Command failed with exit code 1.

```

**Comment by philipp-spiess** [comment]
Oh, strange. I think updating the node version to the one we use (20.4) might help. But I would also go and delete all `node_modules` just to try again.

On CI, we also run `pnpm build` in between the `install` and the other commands: https://github.com/sourcegraph/cody/blob/main/.github/workflows/ci.yml#L31

Perhaps we need to build the shared modules first for some reason?

**Comment by leiwen83** [comment]
> Oh, strange. I think updating the node version to the one we use (20.4) might help. But I would also go and delete all `node_modules` just to try again.
> 
> On CI, we also run `pnpm build` in between the `install` and the other commands: https://github.com/sourcegraph/cody/blob/main/.github/workflows/ci.yml#L31
> 
> Perhaps we need to build the shared modules first for some reason?

hi @philipp-spiess ,

Add "pnpm build" could fix "Failed to resolve entry for package sourcegraph/cody-shared"  issue.
However, while continue with "pnpm run dev", I got below error as:
```
[1] pnpm run -s _build:webviews --mode development exited with code 0
sh: 1: code: not found
 ELIFECYCLE  Command failed with exit code 1.
```

Any idea?

**Comment by philipp-spiess** [comment]
@leiwen83 Looks like VS Code is not setup with the `code` CLI argument, could that be? 

AFAIK this can be done inside VS Code with the following action.

<img width="743" alt="Screenshot 2023-09-06 at 12 51 26" src="https://github.com/sourcegraph/cody/assets/458591/c0473f21-cfd0-4863-b508-85bb6eccfb6d">

--


BTW thank you so much for helping uncover these issues. We mostly develop directly inside VS Code with the "run and debug" feature. So I open the `cody` root in VS Code, go to the Run and Debug tab, select "Launch VS Code extension (desktop)" from the list, and press the play icon.

It seems though that the contributing doc could use a lot of polishing. If you want to contribute, I'd be more than happy to review your PR 🤗

**Comment by jdorfman** [comment]
@leiwen83 can you please confirm :)

**Comment by leiwen83** [comment]
Thx for help, it works

**Comment by Shangguanxingchen** [comment]
Hi,
I try release cody directly from source, but met below error:

PS D:\cody\vscode> pnpm run release:dry-run

> cody-ai@1.6.0 release:dry-run D:\cody\vscode
> pnpm run download-wasm && CODY_RELEASE_DRY_RUN=1 ts-node ./scripts/release.ts


> cody-ai@1.6.0 download-wasm D:\cody\vscode
> ts-node-transpile-only ./scripts/download-wasm-modules.ts

All wasm modules are in place, have a good day!
'CODY_RELEASE_DRY_RUN' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
 ELIFECYCLE  Command failed with exit code 1.
PS D:\cody\vscode>
